export type { FootnoteMap, FootnoteZone } from "./types"
export { detectHtmlFootnotes } from "./htmlDetector"
export { detectTextFootnotes } from "./textDetector"
export { detectFootnotes } from "./detectFootnotes"
export { tagCitationsWithFootnotes } from "./tagging"
