/**
 * Codegen: turn data/reporters.json into src/data/reporters.gen.ts
 *
 * The generated module wraps the JSON payload in `JSON.parse('…')` rather
 * than as an object literal. V8 evaluates JSON.parse(string) on a faster path
 * than equivalent object-literal syntax for payloads ≥ ~10 KB
 * (see docs/research/2026-05-21-shipping-large-data-with-tsdown.md).
 *
 * Tsdown / Rolldown auto-code-splits the dynamic `await import("./reporters.gen.js")`
 * call site in src/data/reporters.ts into a separate ESM + CJS chunk in dist/,
 * preserving lazy-loading semantics without any tsdown.config.ts changes.
 */
import { readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const jsonPath = resolve(root, "data/reporters.json")
const outPath = resolve(root, "src/data/reporters.gen.ts")

const raw = await readFile(jsonPath, "utf8")
JSON.parse(raw) // validate the input is well-formed JSON

// JSON.stringify on a string yields a JS string literal — exactly what we
// need to embed inside `JSON.parse(…)`. Single round-trip handles all escaping.
const literal = JSON.stringify(raw)

const content = `// AUTOGENERATED by scripts/generate-reporters-data.ts — DO NOT EDIT.
// Regenerate via \`pnpm data:generate\` (also runs in \`prebuild\`).
import type { ReporterEntry } from "./reporters"

const data: Record<string, ReporterEntry[]> = JSON.parse(${literal})
export default data
`

let existing = ""
try {
  existing = await readFile(outPath, "utf8")
} catch {
  // file doesn't exist yet — first run
}

if (existing === content) {
  console.log("reporters.gen.ts is up to date")
} else {
  await writeFile(outPath, content)
  console.log(`Wrote ${outPath} (${(content.length / 1024).toFixed(1)} KB)`)
}
